/**
 * Türkiye Vergi Daireleri listesi.
 * Kayıt ve firma bilgileri formlarında dropdown olarak kullanılır.
 */
export const VERGI_DAIRELERI = [
  "Abana VD.",
  "Acıgöl VD.",
  "Adalar VD.",
  "Adapazarı VD.",
  "Adıyaman VD.",
  "Afyon VD.",
  "Ağrı VD.",
  "Akçakoca VD.",
  "Akdağmadeni VD.",
  "Akdeniz VD.",
  "Akhisar VD.",
  "Aksaray VD.",
  "Alanya VD.",
  "Alaşehir VD.",
  "Altındağ VD.",
  "Altınordu VD.",
  "Amasya VD.",
  "Anamur VD.",
  "Ankara Kurumlar VD.",
  "Ankara Motorlu Taşıtlar VD.",
  "Ankara Ostim VD.",
  "Antakya VD.",
  "Antalya VD.",
  "Ardahan VD.",
  "Artvin VD.",
  "Atışalanı VD.",
  "Avcılar VD.",
  "Aydın VD.",
  "Ayrancı VD.",
  "Bağcılar VD.",
  "Bahçelievler VD.",
  "Bakırköy VD.",
  "Balıkesir VD.",
  "Bandırma VD.",
  "Başakşehir VD.",
  "Batman VD.",
  "Bayrampaşa VD.",
  "Bergama VD.",
  "Beyazıt VD.",
  "Beykoz VD.",
  "Beyoğlu VD.",
  "Beyşehir VD.",
  "Bilecik VD.",
  "Bingöl VD.",
  "Bitlis VD.",
  "Bolu VD.",
  "Bornova VD.",
  "Buca VD.",
  "Burdur VD.",
  "Büyükçekmece VD.",
  "Büyük Mükellefler VD.",
  "Çanakkale VD.",
  "Çankaya VD.",
  "Çarşamba VD.",
  "Çatalca VD.",
  "Çekirge VD.",
  "Çorlu VD.",
  "Çorum VD.",
  "Denizli VD.",
  "Diyarbakır VD.",
  "Düzce VD.",
  "Edirne VD.",
  "Elazığ VD.",
  "Ereğli VD.",
  "Erzincan VD.",
  "Erzurum VD.",
  "Eskişehir VD.",
  "Fatih VD.",
  "Fethiye VD.",
  "Gaziantep VD.",
  "Gebze VD.",
  "Giresun VD.",
  "Gölbaşı VD.",
  "Güngören VD.",
  "Hakkari VD.",
  "Hatay VD.",
  "Isparta VD.",
  "İnegöl VD.",
  "İskenderun VD.",
  "İstanbul Kurumlar VD.",
  "İzmir Kurumlar VD.",
  "Kadıköy VD.",
  "Kahramanmaraş VD.",
  "Karşıyaka VD.",
  "Kartal VD.",
  "Kayseri VD.",
  "Keçiören VD.",
  "Kocaeli VD.",
  "Konya VD.",
  "Kütahya VD.",
  "Lüleburgaz VD.",
  "Malatya VD.",
  "Manisa VD.",
  "Mardin VD.",
  "Mersin VD.",
  "Muğla VD.",
  "Nevşehir VD.",
  "Niğde VD.",
  "Ordu VD.",
  "Osmaniye VD.",
  "Pendik VD.",
  "Rize VD.",
  "Sakarya VD.",
  "Samsun VD.",
  "Siirt VD.",
  "Sinop VD.",
  "Sivas VD.",
  "Söke VD.",
  "Şanlıurfa VD.",
  "Şırnak VD.",
  "Tarsus VD.",
  "Tekirdağ VD.",
  "Tokat VD.",
  "Trabzon VD.",
  "Tuzla VD.",
  "Uşak VD.",
  "Van VD.",
  "Yalova VD.",
  "Yozgat VD.",
  "Zonguldak VD.",
] as const;

export type VergiDairesi = (typeof VERGI_DAIRELERI)[number];
